development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://vfsqijyntoowpw:Sr06TboEKDjvSMF6qeVUnHbUju@ec2-50-19-222-159.compute-1.amazonaws.com:5432/dak3mqn77vfdgb

